apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: production
  labels:
    app: homepage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homepage # indicates which Pods (with which labeles) need be handled by this Deployment
  template:
    metadata: # indicates the metadata that will be added to each Pod
      labels:
        app: homepage
    spec:
      imagePullSecrets:
        - name: regcred
      containers: # defines a running container inside the Pod
        - name: homepage
          image: danieltmcc/homepage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # which port of the container is exposed to the Pod
          # env:
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
